FROM w251/cuda:dev-tx2-4.3_b132
RUN sudo apt-get -y update && sudo apt-get -y upgrade
RUN sudo apt-get install -y python3-numpy
RUN sudo apt-get install -y python3-opencv
RUN sudo apt install -y mosquitto-clients
RUN apt-get -y install python3-pip
RUN pip3 install paho-mqtt
